# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='localidad',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
