# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-25 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direcciones', '0002_auto_20180323_2050'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='localidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Localidades', to='direcciones.Localidad', verbose_name='Localidad'),
        ),
    ]
