# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_userprofile_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
