# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20180326_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='imagen',
        ),
    ]
