# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-10 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='precio_compra',
        ),
    ]
