# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20180410_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Precios'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Precios'),
        ),
    ]
