# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20180412_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
