# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-16 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_auto_20180412_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precios',
            name='precio_unitario',
        ),
        migrations.DeleteModel(
            name='Precios',
        ),
    ]
