# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-30 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20180416_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Cantidad disponible'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_de_medida',
            field=models.CharField(choices=[('KG', 'Kilogramos'), ('LT', 'Litros'), ('UN', 'Unidades')], default='UN', max_length=2),
        ),
    ]
