# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-29 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenes',
            field=models.ImageField(default='images/caballero.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Kilogramos'), (2, 'Metros'), (3, 'Litros')], null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
